// AUTO-GENERATED hero metadata. id -> {k:cdnKey, n:name, a:attr, w:why}
// Only edit 'w' (descriptions) or add new heroes here.
window.HEROES = {
  1:{k:"antimage",n:"Anti-Mage",a:"agi",w:"Сжигает ману и фармит быстрее всех."},
  2:{k:"axe",n:"Axe",a:"str",w:"«Berserker's Call» затаскивает врагов под команду."},
  3:{k:"bane",n:"Bane",a:"int",w:"«Fiend's Grip» выключает цель на весь файт."},
  5:{k:"crystal_maiden",n:"Crystal Maiden",a:"int",w:"Аура маны для всех + «Freezing Field» в кучу."},
  6:{k:"drow_ranger",n:"Drow Ranger",a:"agi",w:"Аура на скорость атаки усиливает весь пуш команды."},
  7:{k:"earthshaker",n:"Earthshaker",a:"str",w:"«Echo Slam» в одиночку выигрывает файт."},
  8:{k:"juggernaut",n:"Juggernaut",a:"agi",w:"«Omnislash» с иммунитетом — надёжный убийца целей."},
  9:{k:"mirana",n:"Mirana",a:"uni",w:"«Sacred Arrow» и «Moonlight Shadow» через всю карту."},
  11:{k:"nevermore",n:"Shadow Fiend",a:"agi",w:"«Requiem of Souls» — дикий бурст по собранным целям."},
  12:{k:"phantom_lancer",n:"Phantom Lancer",a:"agi",w:"Армия иллюзий — кошмар для физического дамага врага."},
  13:{k:"puck",n:"Puck",a:"uni",w:"«Dream Coil» собирает врага, сам легко выживает."},
  14:{k:"pudge",n:"Pudge",a:"str",w:"«Hook» выдёргивает цель прямо под команду."},
  17:{k:"storm_spirit",n:"Storm Spirit",a:"int",w:"«Ball Lightning»: догонит и убьёт по всей карте."},
  22:{k:"zuus",n:"Zeus",a:"int",w:"«Thundergod's Wrath» бьёт по всей карте."},
  23:{k:"kunkka",n:"Kunkka",a:"str",w:"«Torrent» + «X Marks»: контроль и AoE в файте."},
  25:{k:"lina",n:"Lina",a:"int",w:"Огромный бурст и дальний стан «Light Strike Array»."},
  26:{k:"lion",n:"Lion",a:"int",w:"«Earth Spike» + «Hex» + «Finger»: полный контроль и добивание."},
  27:{k:"shadow_shaman",n:"Shadow Shaman",a:"int",w:"«Mass Serpent Ward» сносит вышку за секунды."},
  28:{k:"slardar",n:"Slardar",a:"str",w:"«Corrosive Haze» снимает броню и «Slithereen Crush» лочит."},
  29:{k:"tidehunter",n:"Tidehunter",a:"str",w:"«Ravage» — массовый стан, мечта любого вомбо-комбо."},
  30:{k:"witch_doctor",n:"Witch Doctor",a:"int",w:"«Death Ward»: дикий урон по собранным целям."},
  31:{k:"lich",n:"Lich",a:"int",w:"«Frost Shield» на пуш и «Chain Frost» в кучу."},
  33:{k:"enigma",n:"Enigma",a:"uni",w:"«Black Hole» — главный «соберись и умри» ульт."},
  34:{k:"tinker",n:"Tinker",a:"int",w:"Бесконечные «Rearm»-нюки и пуш с любой точки."},
  35:{k:"sniper",n:"Sniper",a:"agi",w:"Радиус и «Assassinate» через карту."},
  36:{k:"necrolyte",n:"Necrophos",a:"int",w:"Хил, мана и «Reaper's Scythe» — мотор затяжных файтов."},
  39:{k:"queenofpain",n:"Queen of Pain",a:"int",w:"Блинк и бурст-магия — идеальный мидер под ганг."},
  41:{k:"faceless_void",n:"Faceless Void",a:"uni",w:"«Chronosphere» решает файты — играй вокруг него."},
  44:{k:"phantom_assassin",n:"Phantom Assassin",a:"agi",w:"Криты и «Blur»: фармит и удаляет цель за пару ударов."},
  45:{k:"pugna",n:"Pugna",a:"int",w:"«Nether Blast» бьёт по строениям — машина осады."},
  48:{k:"luna",n:"Luna",a:"agi",w:"«Eclipse» и глефы с отскоком — машина по AoE-урону."},
  51:{k:"rattletrap",n:"Clockwerk",a:"uni",w:"«Hookshot» влетает и фиксирует цель станом."},
  54:{k:"life_stealer",n:"Lifestealer",a:"str",w:"«Infest» в инициатора — внезапный выскок и неубиваемость."},
  56:{k:"clinkz",n:"Clinkz",a:"agi",w:"Невидимый бурст: выцепляет одиночек, сносит вышки."},
  60:{k:"night_stalker",n:"Night Stalker",a:"uni",w:"Ночью доминирует: ловит врагов в темноте."},
  62:{k:"bounty_hunter",n:"Bounty Hunter",a:"uni",w:"Инвиз, «Track» и золото за пикофы — двигатель снежка."},
  67:{k:"spectre",n:"Spectre",a:"agi",w:"«Haunt» в любой файт по всей карте — идеальный поздний кэрри."},
  69:{k:"doom_bringer",n:"Doom",a:"str",w:"«Doom» выключает ключевого героя на весь файт."},
  70:{k:"ursa",n:"Ursa",a:"agi",w:"«Fury Swipes» рвут любую одиночную цель за секунды."},
  71:{k:"spirit_breaker",n:"Spirit Breaker",a:"uni",w:"«Charge» через всю карту — фиксирует цель для ганга."},
  74:{k:"invoker",n:"Invoker",a:"uni",w:"Швейцарский нож: сбор «Tornado», AoE «Cataclysm», пуш."},
  75:{k:"silencer",n:"Silencer",a:"uni",w:"«Global Silence» отключает все ульты в нужный момент."},
  76:{k:"obsidian_destroyer",n:"Outworld Destroyer",a:"uni",w:"Фарм-мид с уроном по мане, прикрывает кэрри."},
  83:{k:"treant",n:"Treant Protector",a:"str",w:"«Living Armor» лечит всю команду глобально и танкует."},
  85:{k:"undying",n:"Undying",a:"str",w:"«Tombstone» и кража силы — давит линию и тащит в раш."},
  86:{k:"rubick",n:"Rubick",a:"uni",w:"«Spell Steal» крадёт лучший ульт врага и бьёт им же."},
  87:{k:"disruptor",n:"Disruptor",a:"int",w:"«Static Storm» + «Glimpse»: запирает и возвращает врагов."},
  88:{k:"nyx_assassin",n:"Nyx Assassin",a:"uni",w:"«Vendetta» выцеливает кор-героев и душит мидера."},
  90:{k:"keeper_of_the_light",n:"Keeper of the Light",a:"uni",w:"«Illuminate» пушит глобально и кормит команду маной."},
  91:{k:"wisp",n:"Io",a:"uni",w:"«Relocate» и «Tether»: телепорт кэрри в файт и из него."},
  92:{k:"visage",n:"Visage",a:"uni",w:"Птицы-фамильяры стаком сносят цель и строения."},
  93:{k:"slark",n:"Slark",a:"agi",w:"Снежит с пикофов: украл стат — стал сильнее."},
  97:{k:"magnataur",n:"Magnus",a:"uni",w:"«Reverse Polarity» — лучший массовый сбор в игре."},
  100:{k:"tusk",n:"Tusk",a:"str",w:"«Snowball» влетает в гущу и фиксирует цель."},
  104:{k:"legion_commander",n:"Legion Commander",a:"uni",w:"«Duel» один-на-один и бесконечный урон с побед."},
  105:{k:"techies",n:"Techies",a:"uni",w:"Мины и «Blast Off!» — наказывает за любую ошибку."},
  106:{k:"ember_spirit",n:"Ember Spirit",a:"agi",w:"«Fire Remnant»: влетел, убил, вышел сухим."},
  107:{k:"earth_spirit",n:"Earth Spirit",a:"uni",w:"Цепочка контроля и мобильность — затаскивает в команду."},
  109:{k:"terrorblade",n:"Terrorblade",a:"uni",w:"Иллюзии и «Sunder»: дикий кэрри под защиту."},
  110:{k:"phoenix",n:"Phoenix",a:"uni",w:"«Supernova» переворачивает файты + AoE и хил."},
  120:{k:"pangolier",n:"Pangolier",a:"uni",w:"«Rolling Thunder» — мобильный массовый контроль."},
  121:{k:"grimstroke",n:"Grimstroke",a:"int",w:"«Soulbind» связывает врагов под цепной контроль."},
  123:{k:"hoodwink",n:"Hoodwink",a:"uni",w:"«Sharpshooter» бурстит издалека, «Bushwhack» лочит."},
  126:{k:"void_spirit",n:"Void Spirit",a:"uni",w:"Мобильный бурст-мид — кошмар для одиночек."},
  128:{k:"snapfire",n:"Snapfire",a:"uni",w:"Дальний контроль и бурст «Mortimer Kisses»."},
  129:{k:"mars",n:"Mars",a:"str",w:"«Arena» запирает врага в стенах — пикоф без побега."},
  135:{k:"dawnbreaker",n:"Dawnbreaker",a:"uni",w:"«Solar Guardian»: глобальный сейв и хил в файте."},
  136:{k:"marci",n:"Marci",a:"uni",w:"«Unleash» и «Rebound»: инициация и ближний урон."}
};
